version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: douma_postgres
    restart: always
    environment:
      POSTGRES_USER: douma
      POSTGRES_PASSWORD: password
      POSTGRES_DB: douma_dental
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
